# Generated by Django 4.0.4 on 2022-06-25 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_reg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=50)),
                ('phone_number', models.BigIntegerField()),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
